import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card'
import { CalendarDays, Receipt, Wallet, Stethoscope } from 'lucide-react'

interface Props {
  appointments: any
  billing: any
}

export default function SummaryStatsCard({ appointments, billing }: Props) {
  const apptList: any[] = Array.isArray(appointments)
    ? appointments
    : Array.isArray((appointments as any)?.appointments)
      ? (appointments as any).appointments
      : Array.isArray((appointments as any)?.data?.appointments)
        ? (appointments as any).data.appointments
        : Array.isArray((appointments as any)?.data)
          ? (appointments as any).data
          : []

  const billList: any[] = Array.isArray(billing)
    ? billing
    : Array.isArray((billing as any)?.billing)
      ? (billing as any).billing
      : Array.isArray((billing as any)?.data?.billing)
        ? (billing as any).data.billing
        : Array.isArray((billing as any)?.data)
          ? (billing as any).data
          : []

  const totalPending = billList
    .filter((b) => b.status === 'Pending')
    .reduce((acc, b) => acc + (Number(b.total_price) || 0), 0)

  const pendingCount = billList.filter((b) => b.status === 'Pending').length

  return (
    <>
      <Card>
        <CardHeader className="flex flex-row items-center justify-between pb-2">
          <CardTitle className="text-sm font-medium">
            Appointments
          </CardTitle>
          <CalendarDays className="h-4 w-4 text-primary" />
        </CardHeader>
        <CardContent>
          <div className="text-2xl font-bold font-mono">{apptList.length}</div>
          <p className="text-xs text-muted-foreground">Recorded in your profile</p>
        </CardContent>
      </Card>
      <Card>
        <CardHeader className="flex flex-row items-center justify-between pb-2">
          <CardTitle className="text-sm font-medium">Total Invoices</CardTitle>
          <Receipt className="h-4 w-4 text-muted-foreground" />
        </CardHeader>
        <CardContent>
          <div className="text-2xl font-bold font-mono">{billList.length}</div>
          <p className="text-xs text-muted-foreground">Generated by system</p>
        </CardContent>
      </Card>
      <Card>
        <CardHeader className="flex flex-row items-center justify-between pb-2">
          <CardTitle className="text-sm font-medium">Pending Total</CardTitle>
          <Wallet className="h-4 w-4 text-amber-500" />
        </CardHeader>
        <CardContent>
          <div className="text-2xl font-bold font-mono text-amber-600 dark:text-amber-400">
            ${totalPending.toFixed(2)}
          </div>
          <p className="text-xs text-muted-foreground">Balance awaiting payment</p>
        </CardContent>
      </Card>
      <Card>
        <CardHeader className="flex flex-row items-center justify-between pb-2">
          <CardTitle className="text-sm font-medium">
            Pending Invoices
          </CardTitle>
          <Stethoscope className="h-4 w-4 text-muted-foreground" />
        </CardHeader>
        <CardContent>
          <div className="text-2xl font-bold font-mono">{pendingCount}</div>
          <p className="text-xs text-muted-foreground">Open invoices</p>
        </CardContent>
      </Card>
    </>
  )
}
